const mongoose = require("mongoose");
const crypto = require("crypto");

/**
 * User Schema Definition
 * Handles user account management, security, and behavioral tracking
 */
const UserSchema = new mongoose.Schema({
  // Primary user identification - encrypted for security
  encryptedEmail: {
    type: String,
    required: true,
    unique: true,
  },

  // Human-readable ID format: 'USR-' followed by random hex
  // Used in admin interfaces to reference users without exposing email
  systemId: {
    type: String,
    unique: true,
    default: () => "USR-" + crypto.randomBytes(6).toString("hex").toUpperCase(),
  },

  // Secondary encrypted identifier for additional security layer
  // Used in sensitive operations where email exposure should be minimized
  encryptedUserId: {
    type: String,
    unique: true,
    default: () => crypto.randomBytes(16).toString("hex"),
  },

  // Hashed password (hashing should be done pre-save)
  password: {
    type: String,
    required: true,
  },

  // User behavior monitoring system
  warnings: {
    type: Number,
    default: 0,
  },

  // Temporary ban management
  // null indicates no active ban
  banUntil: {
    type: Date,
    default: null,
  },

  // Comprehensive flag tracking system
  // Maintains history of user violations and administrative actions
  flagHistory: [
    {
      reason: {
        type: String,
        enum: [
          "Harassment",
          "Spam",
          "Inappropriate Content",
          "Multiple Violations",
          "Other",
        ],
      },
      feedback: String, // Stored content that triggered the flag
      timestamp: { type: Date, default: Date.now },
      autoGenerated: { type: Boolean, default: true }, // Indicates if flag was system or admin generated
      actionTaken: {
        type: String,
        enum: ["Warning", "Temporary Ban", "Account Review"],
      },
    },
  ],

  // User notification system
  // Handles system messages and administrative communications
  notifications: [
    {
      message: String,
      read: { type: Boolean, default: false },
      timestamp: { type: Date, default: Date.now },
      type: {
        type: String,
        enum: ["warning", "ban", "info", "unban"],
      },
    },
  ],

  // Password reset functionality
  // Tokens expire after a set time for security
  resetPasswordToken: String,
  resetPasswordExpires: Date,

  // Account status tracking
  isActive: {
    type: Boolean,
    default: true,
  },
  lastLogin: Date,
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

/**
 * Virtual Properties
 * Computed properties that don't persist in the database
 */
UserSchema.virtual("isBanned").get(function () {
  return this.banUntil && this.banUntil > new Date();
});

/**
 * Instance Methods
 * Utility functions available on user documents
 */

// Adds a new flag to user's history
UserSchema.methods.addFlag = function (
  reason,
  feedback,
  actionTaken = "Warning"
) {
  this.flagHistory.push({
    reason,
    feedback: feedback.substring(0, 100), // Truncate long feedback
    actionTaken,
    timestamp: new Date(),
  });
  return this.save();
};

// Creates a new notification for the user
UserSchema.methods.addNotification = function (message, type = "info") {
  this.notifications.push({
    message,
    type,
    timestamp: new Date(),
  });
  return this.save();
};

module.exports = mongoose.model("User", UserSchema);
